// naufal-lab/src/App.svelte
<script lang="ts">
  import { t } from '$lib/i18n'

  import Counter from './lib/Counter.svelte'
  import Presence from './lib/Presence.svelte'
</script>

<main class="bg-background text-foreground min-h-dvh">
  <div class="mx-auto max-w-2xl px-6 py-16">
    <header class="mb-8">
      <p class="text-muted-foreground font-mono text-xs">
        naufal-lab · Svelte 5 + Vite
      </p>
      <h1 class="mt-2 text-2xl font-semibold">{$t('app.title')}</h1>
      <p class="text-muted-foreground mt-3 text-sm leading-relaxed">
        {$t('app.descriptionPre')}
        <code class="text-foreground font-mono">remoteEntry.js</code>.
      </p>
    </header>

    <div class="space-y-6">
      <section class="border-border bg-card rounded-xl border p-5 shadow-sm">
        <div class="text-muted-foreground mb-3 font-mono text-xs">
          // exposed: ./Counter
        </div>
        <Counter context="standalone" />
      </section>

      <section class="border-border bg-card rounded-xl border p-5 shadow-sm">
        <div class="text-muted-foreground mb-3 font-mono text-xs">
          // exposed: ./Presence
        </div>
        <Presence context="standalone" />
      </section>
    </div>
  </div>
</main>

// naufal-host/src/App.tsx
import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import { HeroBlock } from '@/components/blocks/HeroBlock'
import { MicrofrontendBlock } from '@/components/blocks/MicrofrontendBlock'
import { PresenceBlock } from '@/components/blocks/PresenceBlock'
import { TechStackBlock } from '@/components/blocks/TechStackBlock'

export default function App() {
  return (
    <div className="flex min-h-dvh flex-col bg-background text-foreground">
      <Header />
      <main className="mx-auto w-full max-w-2xl flex-1 px-6 py-12">
        <p className="mb-10 text-lg leading-relaxed text-muted-foreground sm:text-xl">
          A playground of interactive things I build.
        </p>
        <div className="space-y-6">
          <HeroBlock />
          <TechStackBlock />
          <MicrofrontendBlock />
          <PresenceBlock />
        </div>
      </main>
      <Footer />
    </div>
  )
}
